site_name: Projeto AJNA - Treinamento de modelos
site_description: Followup do treinamento de novos modelos para o AJNA com TensorFlow2.0

nav:
    - Definição: index.md
    - Análise: resumo.md
    - Relatório ChestXRay: notebooks.md
    - Relatório Vazios: notebooks_vazios.md
    - Conclusões: conclusao.md
    - Sobre: sobre.md



theme: material

plugins:
    - search
    - git-revision-date
    #- pdf-export:
    #    combined: true